In [3]:
import numpy as np
import pandas as pd
from random import randrange
from neupy import algorithms
from sklearn.model_selection import train_test_split

In [16]:
dataset_norma = pd.read_csv('output/dataset-normalisasi.csv')
dataset = dataset_norma.loc[:, ~dataset_norma.columns.isin(['ID'])]

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,SPLEEN PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK POSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
CLASS,,,,,,,,,,,,,,,,,,,
0.0,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
1.0,122,122,122,122,122,122,122,122,122,122,122,122,122,122,122,122,122,122,122

In [6]:
train_df, test_df = train_test_split(dataset, test_size=0.1, stratify=dataset.loc[:, ['CLASS']], random_state=0)
train_df = train_df.sort_index()
test_df = test_df.sort_index()

In [19]:
train_df.CLASS

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
147    1.0
148    1.0
149    0.0
151    1.0
153    0.0
Name: CLASS, Length: 138, dtype: float64

In [27]:
test_df.CLASS

10     1.0
15     1.0
20     1.0
32     1.0
35     1.0
36     1.0
43     1.0
61     1.0
71     1.0
81     1.0
97     0.0
105    0.0
128    0.0
141    1.0
150    1.0
152    1.0
Name: CLASS, dtype: float64

In [24]:
dataset_norma.loc[train_df.index]

,ID,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER BIG,LIVER FIRM,...,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK POSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,CLASS
0,1,0.605634,0.0,0.5,1.0,0.5,1.0,1.0,0.5,1.0,...,1.0,1.0,1.0,0.1125,0.457627,0.064815,0.546875,0.00,0.0,1.0
1,2,1.000000,0.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0875,0.325424,0.049383,0.625000,0.00,0.0,1.0
2,3,0.338028,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0875,0.155932,0.080247,0.625000,0.80,0.0,1.0
3,4,0.380282,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.1250,0.000000,0.308642,0.625000,0.00,0.0,1.0
4,5,0.380282,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.1125,0.322034,0.043210,0.625000,0.75,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,148,0.183099,0.0,0.5,1.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,0.1125,0.301695,0.234568,0.625000,0.00,1.0,1.0
148,149,0.408451,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0750,0.406780,0.046296,0.625000,0.00,1.0,1.0
149,150,0.549296,0.0,1.0,1.0,0.5,0.5,0.5,1.0,1.0,...,0.5,0.5,0.5,0.9500,0.000000,0.373457,0.515625,0.50,1.0,0.0
151,152,0.760563,0.0,0.5,1.0,0.5,0.5,1.0,0.5,0.5,...,0.5,1.0,1.0,0.1000,0.254237,0.030864,0.640625,0.00,1.0,1.0
153,154,0.507042,0.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,...,0.5,0.5,1.0,0.1500,0.338983,0.029321,0.484375,0.42,1.0,0.0

In [30]:
data_train_90 = dataset_norma.loc[train_df.index]
data_test_10 = dataset_norma.loc[test_df.index]
data_train_90.to_csv('output/data-train-90.csv', index=False)
data_test_10.to_csv('output/data-test-10.csv', index=False)